### ISSUE TITLE
ETA on missing Azure resources?

### ISSUE THREAD

**Issue by spartan363** [microsoft/threat-modeling-templates#27]
Do you have an ETA for when the missing Azure resources will be added to the Azure template? For example, we'd like to see the API Management, AD B2C, Function Apps and Azure Firewall as well as other resources added. Thanks.

**Comment by marnheus** [comment]
I'd be interested to see also the AKS service, even if eventually it's a vm scale set and a bunch of other resources, it would be nice to have some self-contained approach to it.

**Comment by parulgarg** [comment]
Hi .. Thanks for reaching out.  We are continuously working on adding new Azure resources stencils into our existing stencil set. With the latest release , we have added Azure Logic Apps and Azure Data Explorer. Also , we do accept community contribution to our templates as you can see "Medical Device Template" .
